### ISSUE TITLE
Deserialization target class for discriminator value: search

### ISSUE THREAD

**Issue by CristianPerezGraj** [IBM/java-sdk-core#167]
Hi,

I´m getting the next issue and I looking for help;

![image](https://user-images.githubusercontent.com/93949918/157988245-04f3fb9f-1225-48b7-9ff0-1294cd01d0d3.png)

Its happening on com.ibm.cloud.sdk.core.util.DiscriminatorBasedTypeAdapterFactory.java line 256, This looks like the assistant its returning more objects as usual and the SDK its generating and issue trying to convert it in LogCollection object.

Thanks in advice for your help.

**Comment by padamstx** [comment]
This error indicates that the service is returning a response object that can't be unmarshalled properly because the value of the discriminator property is "search" but there is no mapping for the value "search" to a viable model class.
This is most likely resulting from using an older version of the SDK whereas the service has been updated to support additional discriminated subtypes (one of which is associated with the "search" value).
Make sure that you are using the latest version of the Watson Java SDK.  If the problem still occurs after that, then you'll need to open an issue with the Watson Java SDK project so they can start the investigation.

**Comment by padamstx** [comment]
Follow-up:  I double-checked the assistant-v1 API definition located here: https://cloud.ibm.com/apidocs/assistant/assistant-v1
and the RuntimeResponseGeneric schema does not define a mapping for the value "search".  So, it looks like perhaps the service is returning a response that doesn't comply with the API definition.

cc: @kevinkowa

**Comment by CristianPerezGraj** [comment]
Yes @padamstx that is correct, Im thinking in this moment that all of those fields are new customized new ones, added in the Watson Assistant Bot, and returned from the API. That why my assumption are the SDK its not prepared for receive custom fields added to the Assistant. I create the entire object structure manually and haves a lot of fields different that the documentation.

Maybe Im wrong on that assumpion?? Im a lot confuse on this. 

If you need a response JSON file with those fields Im able to upload it.

**Comment by repjarms** [comment]
Thanks @padamstx @CristianPerezGraj for discussing this - let me talk through this with the team and see if this is something that needs to be addressed in the API def and the Java SDK.

**Comment by padamstx** [comment]
@CristianPerezGraj It might help in the investigation if you could go ahead and attach a sample response to the issue here.

**Comment by kevinkowa** [comment]
From the looks of it, it might be an issue with using both v1 and v2 API. There's possibly some logs that contain a search response that is not available in v1. Quite strange, but we will add it to our backlog.

v1 runtime API does not return search responses. You can only get search responses from the v2 message API

**Comment by padamstx** [comment]
@kevinkowa It's probably time to open up an issue against the Watson Java SDK and close this one out.
