### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by 19Serhii99** [IBM/java-sdk-core#188]
**okhttp3.Response** marked as **Closeable**.

Shouldn't we _close_ / _wrap with try-with-resources_ this object to prevent memory leaks like this?

```
try (Response response = client.newCall(request).execute()) {
  ...
}
```

Also, I noticed that when running an application on a Kubernetes cluster using this library, an application pod hangs for 5 minutes after the application completed (it's in the Running status within 5 minutes and then marked as Completed). We have a chain / a pipeline of applications running sequentially and this behavior increases the overall time of a job. For example, if the pipeline has 10 applications, then 10 applications * 5 minutes = 50 extra minutes to the end-to-end job. It turned out that **IBM SDK Core** uses the **okhttp3** library under the hood which allocates resources to be released when they are not needed anymore but it's mentioned that cleaning occurs automatically for those resources that have not been used for **X** period of time. In this repository, the **HttpClientSingleton** class is used to control a singleton object to share the same client. When I manually added the following piece of code at the end of the program, Kubernetes pods started completing immediately without waiting for extra 5 minutes:

```
client.dispatcher().executorService().shutdown();
client.connectionPool().evictAll();
```

It was so unobvious and took enought time to investigate what the root cause is. Maybe there is a need to improve / to mention this somewhere in the repo / in the singleton class, or something else to raise awareness of this situation. What do you think of this?

**Comment by padamstx** [comment]
Hi @19Serhii99, 
thank you for raising awareness of this situation.
It sounds like you have done some research on this within the okhttp code and/or documentation. 
Could you share any links to specific documentation that might help me understand the situation a bit better?

Also, I'm just a bit curious... which SDK(s) are you using?

Thanks again!

**Comment by padamstx** [comment]
@19Serhii99,
Regarding your first issue above about needing to close the Response object.  I did some digging to refresh my understanding of the interaction between generated SDK code and the Java core.  

It turns out that there is a standard way in which we read the body of an operation response and that mechanism will close the response body after reading it, which would preclude the need for the application to explicitly close the Response object.
Here's an example from the end of an operation within some generated service code:
```
    ...

    ResponseConverter<Case> responseConverter =
      ResponseConverterUtils.getValue(new com.google.gson.reflect.TypeToken<Case>() { }.getType());
    return createServiceCall(builder.build(), responseConverter);
  }

```
In this example we're creating a response converter to unmarshal an instance of the "Case" class (the return type of the operation) which should be returned in the response body.
The response converter returned by the "getValue()" method is implemented like this:
```
  public static <T> ResponseConverter<T> getValue(final Type type) {
    return new ResponseConverter<T>() {
      @Override
      public T convert(Response response) {
        return ResponseUtils.getValue(response, type);
      }
    };
  }
```
And the ResponseUtils.getValue() method is implemented like this:
```
  public static <T> T getValue(Response response, Type valueType) {
    JsonReader reader;
    try {
      reader = new JsonReader(response.body().charStream());
      return GsonSingleton.getGsonWithoutPrettyPrinting().fromJson(reader, valueType);
    } finally {
      response.body().close();
    }
  }
```
So when the converter is actually called, it just unmarshals the response body into an instance of the class described by "valueType" and then closes the response body.

If you observe a specific situation where you can demonstrate that the response body is not getting closed properly, please let us know.

**Comment by padamstx** [comment]
cc'ing @dpopp07 for awareness
