### ISSUE TITLE
Watson Discovery - IAM apikey authentication error.

### ISSUE THREAD

**Issue by mattique** [IBM/java-sdk-core#64]
I am using Java-SDK to connect to the Watson discovery instance. I am receiving an exception trying to connect by using an API key.

**Code snippet:**
```java
private static final String VERSION = "2019-04-30";
String apikey = "kX462L37.......................KWNEdYyKhtMZYy";
String url = "https://gateway.watsonplatform.net/discovery/api"

try {
	logger.info("discovery initializing...");
	IamOptions options = new IamOptions.Builder()
		.apiKey(apikey).url(url)
		.build();
	discovery = new Discovery(VERSION, options);
	logger.info("discovery initialised");
} catch (Exception e){
	logger.error("Exception initialising discovery: "+e.getMessage(), e);
}
```

**Exception:**

```
[err] Exception in thread "Thread-33" 
[err] com.ibm.cloud.sdk.core.service.exception.ServiceResponseException: Not Found
[err] 	at com.ibm.cloud.sdk.core.service.security.IamTokenManager$1.run(IamTokenManager.java:174)
[err] 	at [internal classes]
[QuestionAnswerHandler:ERROR] Exception: null
java.lang.NullPointerException
	at com.ibm.cloud.sdk.core.service.security.IamTokenManager.requestToken(IamTokenManager.java:127)
	at com.ibm.cloud.sdk.core.service.security.IamTokenManager.getToken(IamTokenManager.java:99)
	at com.ibm.cloud.sdk.core.service.security.IamTokenManager.authenticate(IamTokenManager.java:79)
	at com.ibm.cloud.sdk.core.service.BaseService.setAuthentication(BaseService.java:337)
	at com.ibm.cloud.sdk.core.service.BaseService.createCall(BaseService.java:201)
	at com.ibm.cloud.sdk.core.service.BaseService.createServiceCall(BaseService.java:239)
	at com.ibm.watson.discovery.v1.Discovery.listEnvironments(Discovery.java:258)
	at com.ibm.thcaas.wds.api.DiscoveryClient.getEnvironent(DiscoveryClient.java:117)
	at com.ibm.thcaas.wds.api.DiscoveryClient.getWDSConfiguration(DiscoveryClient.java:286)
```

**Comment by mattique** [comment]
curl -u "apikey":"kX462L37HPj5-----------FNGKWNEdYyKhtMZYy" "https://gateway.watsonplatform.net/discovery/api/v1/environments?version=2019-04-30" successfully returns 2 environments - **system, byod**

**Comment by padamstx** [comment]
The newest version of the Java core (used by the most recent version of the Watson Java SDK) handles authentication differently that previous versions of the Java core so configuring your IAM-related information is a bit different.
But, I think the problem that you're seeing is caused by the fact that you're trying to use your service's default URL with the IAM authenticator, which is incorrect.   Perhaps you could try a scenario where you initialize the IamOptions like this instead:
```
	IamOptions options = new IamOptions.Builder()
		.apiKey(apikey)
		.build();
```
essentially just removing the call to the "Builder.url()" method.   This will cause the IAM authenticator to use the default IAM url.

Ordinarily, we'd also to fix the NullPointerException that is occurring, but in this case the IAM authentication code has already undergone some significant changes in the newest version of the Java core so it probably doesn't make sense to do that at this point.
